allow_mixing

component Executable {
    file main
}

component WordWriterLib {
    class WordWriter {
        void printToUpper()
    }
    class Output {
        void write()
    }
    class iostream

    WordWriter *-- Output
    Output <-- iostream
}

Executable <-- WordWriterLib
