allow_mixing

component Executable {
    file main
}

component WordWriterLib {
    class WordWriter

    abstract class WordGeneratorInterface
    class WordGenerator 

    abstract class OutputInterface
    class ConsoleOutput 
    class iostream
    class FileOutput

    WordWriter o-- OutputInterface
    WordWriter o-- WordGeneratorInterface

    OutputInterface <|-- ConsoleOutput
    OutputInterface <|-- FileOutput
    WordGeneratorInterface <|-- WordGenerator
    ConsoleOutput <-- iostream
}

Executable <-- WordWriterLib
