allow_mixing

component Executable {
    file main
}

component WordWriterLib {
    class WordWriter
    class WordGenerator 
    class Output 
    class iostream

    WordWriter o-- Output
    WordWriter o-- WordGenerator
    Output <-- iostream
}

Executable <-- WordWriterLib
